import { empty } from "rxjs";

export const RoutersLink = {
    productsUpdate:"productsUpdate/",
    productListUpdate:"productListUpdate/",
    productListEnd:"productListEnd",
    wayToPay:"wayToPay",
    reservationCart:"reservationCart",
    warrantyUpdate:"warrantyUpdate",
    warranty:"warranty",
    billsPaid:"billsPaid",
    bookingAdmin:"bookingAdmin",
    billsPaidAdmin:"billsPaidAdmin",
    billsPaidUpdate:"billsPaidUpdate",
    booking:"booking",
    detailBooking:"detailBooking",
    detailShow:"detailShow",
    proyects:"proyects",
    bookingUpdate:"bookingUpdate/",
    bookingConsult:"bookingConsult/",
    bookingShow:"show",
    proyectsPagination:"proyectsPagination",
    proyectsUpdate:"proyectsUpdate",
    roles:"roles",
    typeProducts:"typeProducts",
    property:"property",
    bulkUploadProperty:"bulkUploadProperty",
    propertyPagination:"pagination",
    propertyServices:"propertyServices",
    services:"services",
    servicesPagination:"services",
    zone:"zone",
    socialStratum:"socialStratum",
    typeClients:"typesClients",
    quality:"quality",
    productList:"productList",
    productListDetail:"productListDetail/",
    products:"products",
    galleryProducts:"galleryProducts",
    gettotaldataDelete:"deleteRegisterEvent/",
    gettotaldatagallery:"gettotaldatagallery/",
    gettotaldata:"gettotaldata/",
    initialRegistrationReady:"initialRegistrationReady/",
    assistantDetail:"home/listRecordsMade/assistantList/assistantDetail/",
    assistant:"home/reservationList/listCustomerInvoices/",
    purchaseOperatorsDetail:"home/purchaseOperators/purchaseOperatorsDetail/",
    register: "register",
    indexgetgoin:"indexgetgoin",
    registerUpdate: "registerUpdate",
    imgUpdate:"imgUpdate",
    registerChallenge:"registerChallenge",
    registerExpoAllies: "registerExpoAllies",
    passwordUpdate:"passwordUpdate",
    home:"/home/dashboard",
    content:"home/content",
    detail:"home/detailMovies",
    genericPdf:"/genericPdf",
    contentClients:"home/clients/content",
    profile:"home/profile",
    login:"/",
    movies:"movies/now_playing",
    actors:"movies/",
    loginApi:"auth/login",
    refresh:"auth/refresh",
    popular:"movies/popular",
    forgotPassword:"forgotPassword/",
    city:"city",
    category:"category",
    status:"status/",
    getUsersData:"getUsersData/",
    benefits:"benefits",
    scale:"scale",
    challenges:"challenges",
    customerDetail:"customerDetails/",
    menu:"menu/",
    menuIdRol:'menu/idRol/',
    gettotal:"gettotal?id=",
    createEventosGetfinal:"create_eventos_getfinal?idClientsProjects=",
    getEvent:"list",
    users:"users",
    getEventList:"proyects",
    getEventListPost:"institutionHeadquarters",
    getEventPost:"proyects",
    getEventImg:"listRegisterImageEventsList?idClientsProjects=",
    deleteRegisterImageEvent:"deleteRegisterImageEvent/",
    resgisterImageEvents:"resgisterImageEvents",
    assignUserAudit:"assignUserAudit/",
    bulkUploadZone:"bulkUploadZone",
    bulkUploadUsers:"bulkUploadUsers",
    assignUserAuditReady:"assignUserAuditReady/",
    assignUserAuditPost:"assignUserAudit",
    operator:"operator/",
    operatorPost:"operator",
    customerDetailPost:"customerDetails",
    listCustomer:"listCustomer/",
    listUsers:"listUsers/",
    supplier:"supplier",
    supplierPagination:"supplierPagination",
    supplierUpdate: "supplierUpdate",
    merchandiseEntry:"merchandiseEntry",
    merchandiseEntryPagination:"merchandiseEntryPagination",
    merchandiseEntryDetail:"merchandiseEntryDetail",
    merchandiseEntryDetailPagination:"merchandiseEntryDetailPagination",
    buyGraphGeneral:"buyGraphGeneral",
    totalSales:"totalSales",
    buyGraphGeneralProduct:"buyGraphGeneralProduct",
    buyGraphGeneralClients:"buyGraphGeneralClients",
    addProperty:"/home/customer/addProperty/",
    addBilledPeriods:"/home/listInvoices/billingPeriod/listBills/",
    periods:"periods",
    billedPeriods:"billedPeriods",
    bills:"bills",
    accumulatedDebts:"accumulatedDebts",
    queryBills:"queryBills",
    debts:"debts",
    invoicePayment:"invoicePayment",
    noveltyInvoice:"noveltyInvoice",
    fixedCharge:"fixedCharge",
    assign:"accumulatedDebts/assign",
};

export const Menssage = {
    detail:"detail",
    idRolAdmin: 1,
    idRolAdminClientsVigilant: 3,
    idRolAdminClients: 2,
    select: 0,
    bolean: true,
    dataPrint:"dataPrint",
    acccess:"acccess",
    color:"El color es obligatorio",
    title:"El titulo es obligatorio",
    imgLogo:"El logo es obligatorio",
    serverNull:"Cancelaste el la reserva",
    nameOperators:"",
    companyIdentity:"",
    idinstitutionHeadquarters:"",
    idusersuper:"",
    name:"",
    surname:"",
    passwordVerifi:"",
    idrol:"",
    passwordClient:"La contraseña es obligatoria",
    description:"",
    daneCorregimiento:"",
    corregimiento:"",
    daneSedeInstitutions:"",
    sedeInstitutions:"",
    idEducationalInstitutions:"",
    zode:"El zode es obligatorio",
    daneMunicipality:"El No. de DANE del municipio es Obligatorio",
    municipality:"El nombre del municipio es obligatorio",
    daneInstitutions:"El No. de DANE de la institución es Obligatorio",
    institutions:"El nombre de la institución es obligatorio",
    rector:"El nombre del rector es obligatorio",
    telephone:"El No. de teléfono es obligatorio",
    direction:"La dirección es obligatoria",
    idusers:"El intentificador de usuario es obligatorio",
    idProyectsClients:"El identificador de proyecto es obligatorio",
    idImg:"No haz agregado una imagen",
    idEvents:"No haz seleccionado un evento",
    nameEvents:"softsaenz",
    nameProduct:"Listado_de_productos_mas_vendido",
    nameProductGeneral:"Listado_de_productos_general",
    nameEventsNull:"No hay datos que descargar",
    passwordAES:"Softsaenz2023*",
    error:"Error",
    info:"Información",
    token:"token",
    customerDetail:"customerDetails",
    menu:"menu",
    reserve:"Reserva realizada correctamente en unos momentos se estaran comunicado con usted para confirmar su reserva",
    server:"En la conexión del servidor",
    userValid:"El correo ya se encuentra registrado",
    emailValid:"El Email ingresado no se encuentra registrado",
    businessName: "La razón social es obligatoria",
    identificationCard: "El numero de identificación es obligatorio",
    idCategoryToRegister: "La categoria es obligatoria",
    address: "La dirección es obligatoria",
    phone: "El teléfono es obligatorio",
    idCity: "La ciudad es obligatoria",
    email: "El username es obligatorio",
    nit: "El nit no es valido",
    empty: "",
    birthDate:"2020/12/19",
    passwordClientGeneric: "AcueBarClients",
    valiEmail: '^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+$',
    validNumber: /^[1-9]\d{6,10}$/,
    success: "Usuario registrado correctamente",
    successUpdate: "Usuario actualizado correctamente",
    successDelete: "Registro eliminado correctamente",
    successForgot: "Ha tu correo registrado enviamos un link para la recuperación de la contraseña",
    exito:"Exito",
    password: "La contraseña es obligatoria",
    updatePassword: "La contraseña y el correo fueron actualizado correctamente",
    habeas: false,
    habeasDataText:"Debes aceptar las política​ de habeas data",
    personalDataPolicy:"Debes acpetar los términos y condiciones",
    monthlyBudget:"El presupuesto mensual es obligatorio",
    contactPerson:"La persona de contacto es obligatorio",
    successExpo: "El registrado se ralizó correctamente",
};